In [67]:
! pip install pandas 
! pip install datetime 

import pandas as pd
from datetime import datetime

students_records = [
    {
        "Name": "Liyuan",
        "Year": datetime(1991, 2, 22),

        "Assessments": {
            "Math": pd.DataFrame({
                "Assignment": ["Homework 1", "Homework 2", "Midterm", "Final"],
                "Score": [88, 92, 90, 96]
            }),

            "English": pd.DataFrame({
                "Assignment": ["Essay 1", "Essay 2", "Presentation", "Final"],
                "Score": [85, 89, 94, 91]
            }),

            "Physics": pd.DataFrame({
                "Assignment": ["Lab 1", "Lab 2", "Midterm", "Final"],
                "Score": [95, 98, 93, 100]
            })
        }
    },

    {
        "Name": "Brett",
        "Year": datetime(1990, 11, 23),

        "Assessments": {
            "Math": pd.DataFrame({
                "Assignment": ["Homework 1", "Homework 2", "Midterm", "Final"],
                "Score": [65, 72, 68, 75]
            }),

            "English": pd.DataFrame({
                "Assignment": ["Essay 1", "Essay 2", "Presentation", "Final"],
                "Score": [92, 95, 88, 97]
            }),

            "Physics": pd.DataFrame({
                "Assignment": ["Lab 1", "Lab 2", "Midterm", "Final"],
                "Score": [70, 75, 68, 72]
            }),

            "Cars": pd.DataFrame({
                "Assignment": ["Engine Test", "Driving Test", "Final"],
                "Score": [95, 100, 98]
            })
        }
    },

    {
        "Name": "Alice",
        "Year": datetime(1992, 6, 15),

        "Assessments": {
            "Math": pd.DataFrame({
                "Assignment": ["Homework 1", "Homework 2", "Midterm", "Final"],
                "Score": [91, 94, 89, 93]
            }),

            "Physics": pd.DataFrame({
                "Assignment": ["Lab 1", "Lab 2", "Midterm", "Final"],
                "Score": [88, 90, 92, 95]
            }),

            "Computer Science": pd.DataFrame({
                "Assignment": ["Python", "Algorithms", "Project", "Final"],
                "Score": [96, 91, 98, 94]
            })
        }
    }
]

Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.9.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: datetime in /opt/conda/lib/python3.11/site-packages (6.0)
Requirement already satisfied: zope.interface in /opt/conda/lib/python3.11/site-packages (from datetime) (8.6)
Requirement already satisfied: pytz in /opt/conda/lib/python3.11/site-packages (from datetime) (2024.1)

# 🐍 Python Practice — Nested Dictionaries, DataFrames, Loops & Sets

Use the `students_records` dataset to complete the following exercises.

---

## 1. Basic Access

- Print Brett's `"Year"`.
- Print Alice's complete `"Physics"` DataFrame.
- Print Liyuan's score for `"Midterm"` in Math.

---

## 2. Loop Through Records

Write a `for` loop that prints every student's name and all the subjects they take.

Your output should look conceptually like:

    Liyuan: Math, English, Physics
    Brett: Math, English, Physics, Cars
    Alice: Math, Physics, Computer Science

---

## 3. Practise `.items()`

For Liyuan, loop through `"Assessments"` using `.items()`.

For each subject:

- Print the subject name.
- Calculate the average score.
- Print the average score.

Do **not** manually specify `"Math"`, `"English"`, `"Physics"`, etc.

---

## 4. Find Common Subjects Using Sets

Use Python sets to:

1. Find the subjects that **Liyuan and Brett both take**.
2. Find the subjects that **all three students take**.

---

## 5. Find Unique Subjects

Use set operations to find:

1. The subjects Brett takes that Liyuan does **not** take.
2. The subjects Alice takes that **neither Liyuan nor Brett takes**.

---

## 6. Compare Performance

For every subject shared by **Liyuan and Brett**:

1. Calculate Liyuan's average assessment score.
2. Calculate Brett's average assessment score.
3. Print both averages.
4. Determine which student has the higher average.

Your output could look conceptually like:

    Subject: Math
    Liyuan average: ...
    Brett average: ...
    Higher average: ...

---

## 7. Work with DataFrames

For **every student and every subject**, find:

- Their highest individual assessment score.
- The assignment corresponding to that highest score.

Your code should work without knowing beforehand:

- How many students there are.
- How many subjects each student takes.
- How many assignments each subject contains.

---

## 8. Create a Summary DataFrame

Create a new DataFrame containing **one row per student–subject combination**.

The result should have the following structure:

| Name | Subject | Average | Highest | Lowest |
|------|---------|---------|---------|--------|
| Liyuan | Math | ... | ... | ... |
| Liyuan | English | ... | ... | ... |
| Liyuan | Physics | ... | ... | ... |
| Brett | Math | ... | ... | ... |
| Brett | English | ... | ... | ... |
| ... | ... | ... | ... | ... |

Build this DataFrame **programmatically** from `students_records`.

Do not manually enter the student names or subjects.

---

## 9. Practise `groupby()`

Using the summary DataFrame created in **Question 8**:

### 9.1 Average Performance by Student

Use `groupby()` to calculate the **mean of the subject averages for each student**.

### 9.2 Average Performance by Subject

Use another `groupby()` to calculate the **average performance for each subject across all students who take that subject**.

---

## 10. Challenge — Common Assignments with `zip()`

Liyuan and Brett both take Math.

Use `zip()` to pair their Math assignment scores together.

For every pair, calculate:

    Liyuan score - Brett score

For example, conceptually:

    Homework 1: ...
    Homework 2: ...
    Midterm: ...
    Final: ...

### Think About It

When could `zip()` give you a **misleading comparison**?

Consider:

- What if the two students have different numbers of assignments?
- What if their assignments appear in a different order?
- What if one student has `"Homework 3"` while the other does not?
- Does `zip()` know anything about the assignment names?

---

## 11. Final Challenge — Build a Comparison Function

Write a function:

    compare_students(students_records, "Liyuan", "Brett")

The function should:

1. Find the two students automatically from `students_records`.
2. Find the subjects they have in common.
3. Calculate each student's average score for every common subject.
4. Calculate the difference between their average scores.
5. Return the results as a Pandas DataFrame.

The resulting DataFrame should look conceptually like:

| Subject | Liyuan_avg | Brett_avg | Difference |
|---------|------------|-----------|------------|
| Math | ... | ... | ... |
| English | ... | ... | ... |
| Physics | ... | ... | ... |

### Additional Test

Your function should also work if you call:

    compare_students(students_records, "Liyuan", "Alice")

without changing the function itself.

## 1. Basic Access

- Print Brett's `"Year"`.
- Print Alice's complete `"Physics"` DataFrame.
- Print Liyuan's score for `"Midterm"` in Math.

---

In [19]:
#print(students_records)

Brett_index = [i for i,students in enumerate(students_records) if students['Name']=='Brett'][0]
Liyuan_index = [i for i, students in enumerate(students_records) if students['Name']=='Liyuan'][0]
Alice_index = [i for i, students in enumerate(students_records) if students['Name']=='Alice'][0]
print(Brett_index,Liyuan_index,Alice_index)

print(f" {students_records[Brett_index]['Name']} was born at {students_records[Brett_index]['Year']}")

display(students_records[Alice_index]['Assessments']['Physics'])
df_Liyuan_math= students_records[Liyuan_index]['Assessments']['Math']
display(df_Liyuan_math)

Liyuan_Midterm_math_score=df_Liyuan_math[df_Liyuan_math['Assignment']=='Midterm']['Score'].iloc[0]
type(Liyuan_Midterm_math_score)

print(f" Liyuan's Midterm math score is  {Liyuan_Midterm_math_score}")

1 0 2
 Brett was born at 1990-11-23 00:00:00

  Assignment  Score
0      Lab 1     88
1      Lab 2     90
2    Midterm     92
3      Final     95

   Assignment  Score
0  Homework 1     88
1  Homework 2     92
2     Midterm     90
3       Final     96

 Liyuan's Midterm math score is  90

In [20]:
for i,students in enumerate(students_records):
    if students['Name'] == 'Brett':
        print (i)

1

## 2. Loop Through Records

Write a `for` loop that prints every student's name and all the subjects they take.

Your output should look conceptually like:

    Liyuan: Math, English, Physics
    Brett: Math, English, Physics, Cars
    Alice: Math, Physics, Computer Science

---

In [21]:
for student in students_records:
    student_name=student['Name']
    student_assessment=student['Assessments']
    print(student_name, [ subject for subject in student_assessment.keys() ])

Liyuan ['Math', 'English', 'Physics']
Brett ['Math', 'English', 'Physics', 'Cars']
Alice ['Math', 'Physics', 'Computer Science']

## 3. Practise `.items()`

For Liyuan, loop through `"Assessments"` using `.items()`.

For each subject:

- Print the subject name.
- Calculate the average score.
- Print the average score.

Do **not** manually specify `"Math"`, `"English"`, `"Physics"`, etc.

---

In [22]:
Liyuan_index=[i for i,student in enumerate(students_records) if student['Name']=='Liyuan'][0]

for subject, results in students_records[Liyuan_index]['Assessments'].items():
    print(subject, results['Score'].mean())

Math 91.5
English 89.75
Physics 96.5

## 4. Find Common Subjects Using Sets

Use Python sets to:

1. Find the subjects that **Liyuan and Brett both take**.
2. Find the subjects that **all three students take**.

---

In [23]:
Liyuan_subjects={ subject for subject in students_records[Liyuan_index]['Assessments'].keys()}
Brett_subjects={ subject for subject in students_records[Brett_index]['Assessments'].keys()}
Alice_subjects={ subject for subject in students_records[Alice_index]['Assessments'].keys()}

common_subjects_LB= Liyuan_subjects & Brett_subjects
print (common_subjects_LB)

common_subjects_LBA= Liyuan_subjects & Brett_subjects & Alice_subjects
print (common_subjects_LBA)

{'English', 'Math', 'Physics'}
{'Math', 'Physics'}

In [24]:
student_subject={}

for student in students_records:
    student_name= student['Name']
    subject=set(student['Assessments'].keys())
    student_subject[student_name]=subject



Liyuan_subjects=student_subject['Liyuan']
print(Liyuan_subjects)

{'Math', 'Physics', 'English'}

## 5. Find Unique Subjects

Use set operations to find:

1. The subjects Brett takes that Liyuan does **not** take.
2. The subjects Alice takes that **neither Liyuan nor Brett takes**.

---

In [25]:
print(Brett_subjects-Liyuan_subjects)

{'Cars'}

In [26]:
Alice_subjects-(Brett_subjects|Liyuan_subjects)

{'Computer Science'}

## 6. Compare Performance

For every subject shared by **Liyuan and Brett**:

1. Calculate Liyuan's average assessment score.
2. Calculate Brett's average assessment score.
3. Print both averages.
4. Determine which student has the higher average.

Your output could look conceptually like:

    Subject: Math
    Liyuan average: ...
    Brett average: ...
    Higher average: ...

---

In [27]:
rows=[]
for student in students_records:
    student_name=student['Name']
    for subject_key, subject_scores in student['Assessments'].items():
        mean_scores=subject_scores['Score'].mean()
        rows.append({'Name':student_name, 'Subject': subject_key,'Mean_score': mean_scores})

#print(rows)

df_means=pd.DataFrame(rows)
display(df_means)

#Liyuan_subject=set(df_means[df_means['Name']=='Liyuan']['Subject'].unique())
Liyuan_subject={a for a in df_means[df_means['Name']=='Liyuan']['Subject'].unique()}
Brett_subject={a for a in df_means[df_means['Name']=='Brett']['Subject'].unique()}

#type(Liyuan_subject)
#print(Liyuan_subject)
#print(Brett_subject)


common_subjects_LB= list(Liyuan_subject & Brett_subject)

print(common_subjects_LB)
print(type(common_subjects_LB))
#All_mean_Liyuan= df_means[df_means['Name']=='Liyuan']['Mean_score'].mean()
#All_mean_Brett=df_means[df_means['Name']=='Brett']['Mean_score'].mean()
#All_mean_Alice=df_means[df_means['Name']=='Alice']['Mean_score'].mean()

#print(df_means.groupby('Name')['Mean_score'].mean().idxmax())
#print(df_means.groupby('Name')['Mean_score'].mean().max())  

for subject in common_subjects_LB:
    #print(subject)
    #type(subject)
    L=df_means[(df_means['Name']=='Liyuan') & (df_means['Subject']==subject)]['Mean_score'].iloc[0]
    B=df_means[(df_means['Name']=='Brett') & (df_means['Subject']==subject)]['Mean_score'].iloc[0]
    print(f" Liyuan's score of {subject} is {L}")
    print(f" Brett's score of {subject} is {B}")
    if L-B>0:
        print(f"Liyuan has a higher score")
    elif L-B<0:
        print (f"Brett has a higher score")
    else:
        print(f"they have the same score")

     Name           Subject  Mean_score
0  Liyuan              Math   91.500000
1  Liyuan           English   89.750000
2  Liyuan           Physics   96.500000
3   Brett              Math   70.000000
4   Brett           English   93.000000
5   Brett           Physics   71.250000
6   Brett              Cars   97.666667
7   Alice              Math   91.750000
8   Alice           Physics   91.250000
9   Alice  Computer Science   94.750000

['English', 'Math', 'Physics']
<class 'list'>
 Liyuan's score of English is 89.75
 Brett's score of English is 93.0
Brett has a higher score
 Liyuan's score of Math is 91.5
 Brett's score of Math is 70.0
Liyuan has a higher score
 Liyuan's score of Physics is 96.5
 Brett's score of Physics is 71.25
Liyuan has a higher score

## 7. Work with DataFrames

For **every student and every subject**, find:

- Their highest individual assessment score.
- The assignment corresponding to that highest score.

Your code should work without knowing beforehand:

- How many students there are.
- How many subjects each student takes.
- How many assignments each subject contains.

---

In [28]:
rows=[]
for student in students_records:
    student_name=student['Name']
    for subject_key, subject_scores in student['Assessments'].items():
        #print(subject_scores)
        #print(type(subject_scores))
        for index, row in subject_scores.iterrows():
            Assignment=row['Assignment']
            Score=row['Score']
            rows.append({'Name':student_name,'Subject':subject_key,'Assignment':Assignment,'Score':Score})
            

#print(rows)

df_all=pd.DataFrame(rows)
display(df_means)

     Name           Subject  Mean_score
0  Liyuan              Math   91.500000
1  Liyuan           English   89.750000
2  Liyuan           Physics   96.500000
3   Brett              Math   70.000000
4   Brett           English   93.000000
5   Brett           Physics   71.250000
6   Brett              Cars   97.666667
7   Alice              Math   91.750000
8   Alice           Physics   91.250000
9   Alice  Computer Science   94.750000

In [29]:
name_list= df_all['Name'].unique()
print(name_list)
subject_list = df_all['Subject'].unique()
print(subject_list)

for name in name_list:
    for subject in subject_list:
        df_highest_score_record=df_all[ (df_all['Name']==name) & (df_all['Subject']==subject)].sort_values('Score',ascending=False ).reset_index(drop=True)
        display(df_highest_score_record)


display(df_all)

df_highest_score= df_all.loc[df_all.groupby(['Name','Subject'])['Score'].idxmax()]
display(df_highest_score)

<StringArray>
['Liyuan', 'Brett', 'Alice']
Length: 3, dtype: str
<StringArray>
['Math', 'English', 'Physics', 'Cars', 'Computer Science']
Length: 5, dtype: str

     Name Subject  Assignment  Score
0  Liyuan    Math       Final     96
1  Liyuan    Math  Homework 2     92
2  Liyuan    Math     Midterm     90
3  Liyuan    Math  Homework 1     88

     Name  Subject    Assignment  Score
0  Liyuan  English  Presentation     94
1  Liyuan  English         Final     91
2  Liyuan  English       Essay 2     89
3  Liyuan  English       Essay 1     85

     Name  Subject Assignment  Score
0  Liyuan  Physics      Final    100
1  Liyuan  Physics      Lab 2     98
2  Liyuan  Physics      Lab 1     95
3  Liyuan  Physics    Midterm     93

Empty DataFrame
Columns: [Name, Subject, Assignment, Score]
Index: []

Empty DataFrame
Columns: [Name, Subject, Assignment, Score]
Index: []

    Name Subject  Assignment  Score
0  Brett    Math       Final     75
1  Brett    Math  Homework 2     72
2  Brett    Math     Midterm     68
3  Brett    Math  Homework 1     65

    Name  Subject    Assignment  Score
0  Brett  English         Final     97
1  Brett  English       Essay 2     95
2  Brett  English       Essay 1     92
3  Brett  English  Presentation     88

    Name  Subject Assignment  Score
0  Brett  Physics      Lab 2     75
1  Brett  Physics      Final     72
2  Brett  Physics      Lab 1     70
3  Brett  Physics    Midterm     68

    Name Subject    Assignment  Score
0  Brett    Cars  Driving Test    100
1  Brett    Cars         Final     98
2  Brett    Cars   Engine Test     95

Empty DataFrame
Columns: [Name, Subject, Assignment, Score]
Index: []

    Name Subject  Assignment  Score
0  Alice    Math  Homework 2     94
1  Alice    Math       Final     93
2  Alice    Math  Homework 1     91
3  Alice    Math     Midterm     89

Empty DataFrame
Columns: [Name, Subject, Assignment, Score]
Index: []

    Name  Subject Assignment  Score
0  Alice  Physics      Final     95
1  Alice  Physics    Midterm     92
2  Alice  Physics      Lab 2     90
3  Alice  Physics      Lab 1     88

Empty DataFrame
Columns: [Name, Subject, Assignment, Score]
Index: []

    Name           Subject  Assignment  Score
0  Alice  Computer Science     Project     98
1  Alice  Computer Science      Python     96
2  Alice  Computer Science       Final     94
3  Alice  Computer Science  Algorithms     91

      Name           Subject    Assignment  Score
0   Liyuan              Math    Homework 1     88
1   Liyuan              Math    Homework 2     92
2   Liyuan              Math       Midterm     90
3   Liyuan              Math         Final     96
4   Liyuan           English       Essay 1     85
5   Liyuan           English       Essay 2     89
6   Liyuan           English  Presentation     94
7   Liyuan           English         Final     91
8   Liyuan           Physics         Lab 1     95
9   Liyuan           Physics         Lab 2     98
10  Liyuan           Physics       Midterm     93
11  Liyuan           Physics         Final    100
12   Brett              Math    Homework 1     65
13   Brett              Math    Homework 2     72
14   Brett              Math       Midterm     68
15   Brett              Math         Final     75
16   Brett           English       Essay 1     92
17   Brett           English       Essay 2     95
18   Brett           English  Presentation     88
19   Brett           English         Final     97
20   Brett           Physics         Lab 1     70
21   Brett           Physics         Lab 2     75
22   Brett           Physics       Midterm     68
23   Brett           Physics         Final     72
24   Brett              Cars   Engine Test     95
25   Brett              Cars  Driving Test    100
26   Brett              Cars         Final     98
27   Alice              Math    Homework 1     91
28   Alice              Math    Homework 2     94
29   Alice              Math       Midterm     89
30   Alice              Math         Final     93
31   Alice           Physics         Lab 1     88
32   Alice           Physics         Lab 2     90
33   Alice           Physics       Midterm     92
34   Alice           Physics         Final     95
35   Alice  Computer Science        Python     96
36   Alice  Computer Science    Algorithms     91
37   Alice  Computer Science       Project     98
38   Alice  Computer Science         Final     94

      Name           Subject    Assignment  Score
37   Alice  Computer Science       Project     98
28   Alice              Math    Homework 2     94
34   Alice           Physics         Final     95
25   Brett              Cars  Driving Test    100
19   Brett           English         Final     97
15   Brett              Math         Final     75
21   Brett           Physics         Lab 2     75
6   Liyuan           English  Presentation     94
3   Liyuan              Math         Final     96
11  Liyuan           Physics         Final    100

In [30]:
results=df_all.groupby(['Name', 'Subject'])['Score'].idxmax()
results.index

MultiIndex([( 'Alice', 'Computer Science'),
            ( 'Alice',             'Math'),
            ( 'Alice',          'Physics'),
            ( 'Brett',             'Cars'),
            ( 'Brett',          'English'),
            ( 'Brett',             'Math'),
            ( 'Brett',          'Physics'),
            ('Liyuan',          'English'),
            ('Liyuan',             'Math'),
            ('Liyuan',          'Physics')],
           names=['Name', 'Subject'])

## 8. Create a Summary DataFrame

Create a new DataFrame containing **one row per student–subject combination**.

The result should have the following structure:

| Name | Subject | Average | Highest | Lowest |
|------|---------|---------|---------|--------|
| Liyuan | Math | ... | ... | ... |
| Liyuan | English | ... | ... | ... |
| Liyuan | Physics | ... | ... | ... |
| Brett | Math | ... | ... | ... |
| Brett | English | ... | ... | ... |
| ... | ... | ... | ... | ... |

Build this DataFrame **programmatically** from `students_records`.

Do not manually enter the student names or subjects.

In [31]:
average = df_all.groupby(['Name','Subject'])['Score'].mean()
highest = df_all.groupby(['Name','Subject'])['Score'].max()
lowest = df_all.groupby(['Name','Subject'])['Score'].min()

display(average)
display(highest)
display(lowest)

df_summary = pd.concat(
    [average.rename('Average'), highest.rename('Highest'), lowest.rename('Lowest')],
    axis=1
).reset_index()

display(df_summary)


df_summary_agg= df_all.groupby(['Name','Subject']).agg(
    Average=('Score','mean'),
    Highest=('Score','max'),
    Lowest=('Score','min'),
    Assignment_counts=('Assignment','count')
   
    
).reset_index()

display(df_summary_agg)

Name    Subject
Alice   Computer Science    94.750000
        Math                91.750000
        Physics             91.250000
Brett   Cars                97.666667
        English             93.000000
        Math                70.000000
        Physics             71.250000
Liyuan  English             89.750000
        Math                91.500000
        Physics             96.500000
Name: Score, dtype: float64

Name    Subject
Alice   Computer Science     98
        Math                 94
        Physics              95
Brett   Cars                100
        English              97
        Math                 75
        Physics              75
Liyuan  English              94
        Math                 96
        Physics             100
Name: Score, dtype: int64

Name    Subject
Alice   Computer Science    91
        Math                89
        Physics             88
Brett   Cars                95
        English             88
        Math                65
        Physics             68
Liyuan  English             85
        Math                88
        Physics             93
Name: Score, dtype: int64

     Name           Subject    Average  Highest  Lowest
0   Alice  Computer Science  94.750000       98      91
1   Alice              Math  91.750000       94      89
2   Alice           Physics  91.250000       95      88
3   Brett              Cars  97.666667      100      95
4   Brett           English  93.000000       97      88
5   Brett              Math  70.000000       75      65
6   Brett           Physics  71.250000       75      68
7  Liyuan           English  89.750000       94      85
8  Liyuan              Math  91.500000       96      88
9  Liyuan           Physics  96.500000      100      93

     Name           Subject    Average  Highest  Lowest  Assignment_counts
0   Alice  Computer Science  94.750000       98      91                  4
1   Alice              Math  91.750000       94      89                  4
2   Alice           Physics  91.250000       95      88                  4
3   Brett              Cars  97.666667      100      95                  3
4   Brett           English  93.000000       97      88                  4
5   Brett              Math  70.000000       75      65                  4
6   Brett           Physics  71.250000       75      68                  4
7  Liyuan           English  89.750000       94      85                  4
8  Liyuan              Math  91.500000       96      88                  4
9  Liyuan           Physics  96.500000      100      93                  4

## 9. Practise `groupby()`

Using the summary DataFrame created in **Question 8**:

### 9.1 Average Performance by Student

Use `groupby()` to calculate the **mean of the subject averages for each student**.

### 9.2 Average Performance by Subject

Use another `groupby()` to calculate the **average performance for each subject across all students who take that subject**.

In [32]:
Average_performence_student= df_summary_agg.groupby('Name')['Average'].mean().reset_index()
Average_performence_subject=df_summary_agg.groupby('Subject')['Average'].mean().reset_index()

display(Average_performence_student)
display(Average_performence_subject)

     Name    Average
0   Alice  92.583333
1   Brett  82.979167
2  Liyuan  92.583333

            Subject    Average
0              Cars  97.666667
1  Computer Science  94.750000
2           English  91.375000
3              Math  84.416667
4           Physics  86.333333

## 10. Challenge — Common Assignments with `zip()`

Liyuan and Brett both take Math.

Use `zip()` to pair their Math assignment scores together.

For every pair, calculate:

    Liyuan score - Brett score

For example, conceptually:

    Homework 1: ...
    Homework 2: ...
    Midterm: ...
    Final: ...

### Think About It

When could `zip()` give you a **misleading comparison**?

Consider:

- What if the two students have different numbers of assignments?
- What if their assignments appear in a different order?
- What if one student has `"Homework 3"` while the other does not?
- Does `zip()` know anything about the assignment names?

---

In [33]:
#display(df_all)

Brett_score=df_all[(df_all['Name']=='Brett')&(df_all['Subject']=='Math')]
Liyuan_score=df_all[(df_all['Name']=='Liyuan')&(df_all['Subject']=='Math')]

print ((Brett_score['Assignment'].to_numpy()==Liyuan_score['Assignment'].to_numpy()).all())
display (Brett_score)
display (Liyuan_score)

for Brett, Liyuan in zip (Brett_score['Score'].to_numpy(), Liyuan_score['Score'].to_numpy()):
    if Brett > Liyuan:
        print('Brett win')
    elif  Brett < Liyuan:
        print ('Liyuan win')
    else: 
        print('they are equal')

True

     Name Subject  Assignment  Score
12  Brett    Math  Homework 1     65
13  Brett    Math  Homework 2     72
14  Brett    Math     Midterm     68
15  Brett    Math       Final     75

     Name Subject  Assignment  Score
0  Liyuan    Math  Homework 1     88
1  Liyuan    Math  Homework 2     92
2  Liyuan    Math     Midterm     90
3  Liyuan    Math       Final     96

Liyuan win
Liyuan win
Liyuan win
Liyuan win

## 11. Final Challenge — Build a Comparison Function

Write a function:

    compare_students(students_records, "Liyuan", "Brett")

The function should:

1. Find the two students automatically from `students_records`.
2. Find the subjects they have in common.
3. Calculate each student's average score for every common subject.
4. Calculate the difference between their average scores.
5. Return the results as a Pandas DataFrame.

The resulting DataFrame should look conceptually like:

| Subject | Liyuan_avg | Brett_avg | Difference |
|---------|------------|-----------|------------|
| Math | ... | ... | ... |
| English | ... | ... | ... |
| Physics | ... | ... | ... |

### Additional Test

Your function should also work if you call:

    compare_students(students_records, "Liyuan", "Alice")

without changing the function itself.

In [88]:
def compare_students(students_records, student1, student2):

    rows=[]
    for student in students_records:
        student_name=student['Name']
        for subject_key, subject_scores in student['Assessments'].items():
            for index, row in subject_scores.iterrows():
                Assignment=row['Assignment']
                Score=row['Score']
                rows.append({'Name':student_name,'Subject':subject_key,'Assignment':Assignment,'Score':Score})

    df_all=pd.DataFrame(rows)   
    student1_subjects=set(df_all[df_all['Name']==student1]['Subject'].unique())
    student2_subjects=set(df_all[df_all['Name']==student2]['Subject'].unique())

    common_subjects= list(student1_subjects & student2_subjects)

    df_average=df_all.groupby(['Name','Subject'])['Score'].mean().reset_index()
    df_average=df_average[(df_average['Subject'].isin(common_subjects))&(df_average['Name'].isin([student1, student2]))].reset_index(drop=True)
    
    sumary_table= df_average.pivot(
        index='Subject',
        columns='Name',
        values='Score'
    ).reset_index()
    sumary_table = sumary_table[['Subject', student1, student2]]

    sumary_table= (sumary_table.rename(
        columns={
            student1:student1+'_averaged',
            student2:student2+'_averaged'
        }
    ))
    sumary_table['Difference']=sumary_table[student1+'_averaged']-sumary_table[student2+'_averaged']


    return sumary_table

sumary_table= compare_students(students_records,'Liyuan','Alice')
display (sumary_table)

print(sumary_table.columns)
print(sumary_table.index)

Name  Subject  Liyuan_averaged  Alice_averaged  Difference
0        Math             91.5           91.75       -0.25
1     Physics             96.5           91.25        5.25

Index(['Subject', 'Liyuan_averaged', 'Alice_averaged', 'Difference'], dtype='str', name='Name')
RangeIndex(start=0, stop=2, step=1)